version: "3.9"
services:
  elasticsearch:
    image: "elasticsearch:7.17.3"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  grafana:
    image: "grafana/grafana:8.3.7"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
  kibana:
    image: "kibana:7.17.3"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
